/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IzborCertifikata.java
 *
 * Created on 22.12.2012., 02:40:09
 */
package Pro3x.Fiscal;

import Acosoft.Processing.Components.Tasks;
import Acosoft.Processing.Pro3App;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.FileInputStream;
import java.security.KeyStore;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.jdesktop.application.Action;
import org.jdesktop.application.LocalStorage;

/**
 *
 * @author aco
 */
public class IzborCertifikata extends javax.swing.JInternalFrame {
    public static final String FINA_XML = "fina.xml";

    private KeyInfo info;
    
    /** Creates new form IzborCertifikata */
    public IzborCertifikata() {
        info = loadKeyInfo();
        initComponents();
        
        putanja.setText(info.getPath());
        zaporka.setText(String.valueOf(info.getPassword()));
        
        ukljuci.setSelected(info.isFiskalizacijaAktivirana());
    }
    
    public static KeyInfo loadKeyInfo()
    {
        try {
            LocalStorage storage = Pro3App.getApplication().getContext().getLocalStorage();
            KeyInfo key = (KeyInfo) storage.load(FINA_XML);
            if(key != null) return key;
        } catch (Exception ex) {
            Logger.getLogger(IzborCertifikata.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return new KeyInfo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ukljuci = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        zaporka = new javax.swing.JPasswordField();
        putanja = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getResourceMap(IzborCertifikata.class);
        setTitle(resourceMap.getString("izbor-certifikata-v4.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(600, 300));
        setName("izbor-certifikata-v4"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 300));

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setName("jPanel3"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getActionMap(IzborCertifikata.class, this);
        jButton2.setAction(actionMap.get("Spremi")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel3.add(jButton2);

        jButton1.setAction(actionMap.get("Zatvori")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel3.add(jButton1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setName("jPanel4"); // NOI18N

        ukljuci.setText(resourceMap.getString("text")); // NOI18N
        ukljuci.setName(""); // NOI18N
        jPanel4.add(ukljuci);

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 2, 0, 2), javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.insideBorder.title")))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jButton3.setAction(actionMap.get("IzborPutanje")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel5.add(jButton3, gridBagConstraints);

        zaporka.setText(resourceMap.getString("zaporka.text")); // NOI18N
        zaporka.setMargin(new java.awt.Insets(2, 2, 2, 2));
        zaporka.setName("zaporka"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(zaporka, gridBagConstraints);

        putanja.setText(resourceMap.getString("putanja.text")); // NOI18N
        putanja.setMargin(new java.awt.Insets(2, 2, 2, 2));
        putanja.setName("putanja"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel5.add(putanja, gridBagConstraints);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 2, 0);
        jPanel5.add(jLabel2, gridBagConstraints);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 2, 0);
        jPanel5.add(jLabel1, gridBagConstraints);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void Spremi() {
        try {
            KeyStore ks = KeyStore.getInstance("PKCS12");
            ks.load(new FileInputStream(putanja.getText()), zaporka.getPassword());

            KeyInfo info = new KeyInfo();
            info.setPassword(zaporka.getPassword());
            info.setPath(putanja.getText());
            info.setFiskalizacijaAktivirana(ukljuci.isSelected());
            
            Pro3App.getApplication().getContext().getLocalStorage().save(info, FINA_XML);
            
            Tasks.showMessage("Detalji o certifikatu su spremljeni. Ako premjestite datoteku, račune više neće biti moguće potpisati.");
            
        } catch (Exception ex) {
            Logger.getLogger(IzborCertifikata.class.getName()).log(Level.SEVERE, null, ex);
            Tasks.showMessage("Ne mogu učitati datoteku sa sigurnosnim certifikatima");
        }
    }

    @Action
    public void Zatvori() {
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(IzborCertifikata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Action
    public void IzborPutanje() {
        JFileChooser xf = new JFileChooser();
        
        xf.setFileFilter(new javax.swing.filechooser.FileFilter() {

            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().endsWith(".pfx");
            }

            @Override
            public String getDescription() {
                return "Sigurnosni ključevi i certifikati ( *.pfx )";
            }
        });
        
        if(xf.showDialog(this.getRootPane(), "Odaberi") == JFileChooser.APPROVE_OPTION)
        {
            putanja.setText(xf.getSelectedFile().getAbsolutePath());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField putanja;
    private javax.swing.JCheckBox ukljuci;
    private javax.swing.JPasswordField zaporka;
    // End of variables declaration//GEN-END:variables
}
