/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IzmjenaPoslovnogProstora.java
 *
 * Created on 22.12.2012., 11:29:16
 */
package Pro3x.Fiscal;

import Acosoft.Processing.Pro3App;
import FinaClient.AdresaType;
import FinaClient.AdresniPodatakType;
import FinaClient.FiskalizacijaPortType;
import FinaClient.PoslovniProstorOdgovor;
import FinaClient.PoslovniProstorType;
import FinaClient.PoslovniProstorZahtjev;
import FinaClient.ZaglavljeType;
import FiscalClient.SecureSoapHandler;
import Pro3x.Configuration.General;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.handler.Handler;
import javax.xml.ws.handler.HandlerResolver;
import javax.xml.ws.handler.PortInfo;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import org.jdesktop.beansbinding.Converter;

/**
 *
 * @author aco
 */
public class IzmjenaPoslovnogProstora extends javax.swing.JInternalFrame {

    private LocationInfo info;
    
    /** Creates new form IzmjenaPoslovnogProstora */
    public IzmjenaPoslovnogProstora() {
        
        info = loadLocationInfo();
        
        initComponents();
        
        getRootPane().setDefaultButton(cmdSpremi);
    }
    
    public static LocationInfo loadLocationInfo()
    {
        try {
            LocationInfo info = (LocationInfo) Pro3App.getApplication().getContext().getLocalStorage().load("location.xml");
            if(info != null) return info;
        } catch (IOException ex) {
            Logger.getLogger(IzmjenaPoslovnogProstora.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return new LocationInfo();
    }
    
    public Converter<Date, String> getDateConverter()
    {
        return new Converter<Date, String>() {

            private SimpleDateFormat sf = new SimpleDateFormat("dd.MM.yyyy");
            
            @Override
            public String convertForward(Date value) {
                return sf.format(value);
            }

            @Override
            public Date convertReverse(String value) {
                try {
                    return sf.parse(value);
                } catch (ParseException ex) {
                    Logger.getLogger(IzmjenaPoslovnogProstora.class.getName()).log(Level.SEVERE, null, ex);
                    
                    SwingUtilities.invokeLater(new Runnable() {

                        @Override
                        public void run() {
                            Calendar cal = Calendar.getInstance();
                            cal.add(Calendar.DATE, 1);
                            
                            datumPromjene.setText(sf.format(cal.getTime()));
                        }
                    });
                    
                    return null;
                }
            }
        };
    }

    public LocationInfo getInfo() {
        return info;
    }

    public void setInfo(LocationInfo info) {
        this.info = info;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cmdSpremi = new javax.swing.JButton();
        cmdZatvori = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        aktivirajPDV = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ulica = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kucniBroj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dodatakKucnomBroju = new javax.swing.JTextField();
        postanskiBroj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        grad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        naselje = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        radnoVrijeme = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nazivLokacije = new javax.swing.JTextField();
        oznakaUredaja = new javax.swing.JTextField();
        nazivLokacije1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        datumPromjene = new javax.swing.JTextField();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getResourceMap(IzmjenaPoslovnogProstora.class);
        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(resourceMap.getString("izmjena-poslovnog-prostora-v4.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(550, 575));
        setName("izmjena-poslovnog-prostora-v4"); // NOI18N
        setPreferredSize(new java.awt.Dimension(550, 575));

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setName("jPanel3"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getActionMap(IzmjenaPoslovnogProstora.class, this);
        cmdSpremi.setAction(actionMap.get("Fiskaliziraj")); // NOI18N
        cmdSpremi.setText(resourceMap.getString("cmdSpremi.text")); // NOI18N
        cmdSpremi.setName("cmdSpremi"); // NOI18N
        cmdSpremi.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel3.add(cmdSpremi);

        cmdZatvori.setAction(actionMap.get("Zatvori")); // NOI18N
        cmdZatvori.setText(resourceMap.getString("cmdZatvori.text")); // NOI18N
        cmdZatvori.setName("cmdZatvori"); // NOI18N
        cmdZatvori.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel3.add(cmdZatvori);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        aktivirajPDV.setText(resourceMap.getString("text")); // NOI18N
        aktivirajPDV.setMargin(new java.awt.Insets(3, 5, 3, 5));
        aktivirajPDV.setName(""); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${info.pdvObveznik}"), aktivirajPDV, org.jdesktop.beansbinding.BeanProperty.create("selected"), "pdv-obveznik");
        bindingGroup.addBinding(binding);

        jPanel4.add(aktivirajPDV);

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 0, 5));
        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 0, 2), javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.insideBorder.title")))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 350));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(150, 18));
        jLabel7.setMinimumSize(new java.awt.Dimension(150, 18));
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 10);
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 18));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 18));
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 10);
        jPanel2.add(jLabel2, gridBagConstraints);

        ulica.setMargin(new java.awt.Insets(2, 2, 2, 2));
        ulica.setName("ulica"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${info.ulica}"), ulica, org.jdesktop.beansbinding.BeanProperty.create("text"), "ulica");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 334;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 10);
        jPanel2.add(ulica, gridBagConstraints);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 18));
        jLabel3.setMinimumSize(new java.awt.Dimension(150, 18));
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 10);
        jPanel2.add(jLabel3, gridBagConstraints);

        kucniBroj.setMargin(new java.awt.Insets(2, 2, 2, 2));
        kucniBroj.setMinimumSize(new java.awt.Dimension(14, 30));
        kucniBroj.setName("kucniBroj"); // NOI18N
        kucniBroj.setPreferredSize(new java.awt.Dimension(14, 30));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${info.broj}"), kucniBroj, org.jdesktop.beansbinding.BeanProperty.create("text"), "kucniBroj");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel2.add(kucniBroj, gridBagConstraints);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 18));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 18));
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 10);
        jPanel2.add(jLabel4, gridBagConstraints);

        dodatakKucnomBroju.setMargin(new java.awt.Insets(2, 2, 2, 2));
        dodatakKucnomBroju.setMinimumSize(new java.awt.Dimension(100, 30));
        dodatakKucnomBroju.setName("dodatakKucnomBroju"); // NOI18N
        dodatakKucnomBroju.setPreferredSize(new java.awt.Dimension(100, 30));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${info.dodatakBroju}"), dodatakKucnomBroju, org.jdesktop.beansbinding.BeanProperty.create("text"), "dodatakBroju");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        jPanel2.add(dodatakKucnomBroju, gridBagConstraints);

        postanskiBroj.setMargin(new java.awt.Insets(2, 2, 2, 2));
        postanskiBroj.setName("postanskiBroj"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${info.postanskiBroj}"), postanskiBroj, org.jdesktop.beansbinding.BeanProperty.create("text"), "postanskiBroj");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 334;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        jPanel2.add(postanskiBroj, gridBagConstraints);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(150, 18));
        jLabel5.setMinimumSize(new java.awt.Dimension(150, 18));
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 10);
        jPanel2.add(jLabel5, gridBagConstraints);

        grad.setMargin(new java.awt.Insets(2, 2, 2, 2));
        grad.setName("grad"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${info.grad}"), grad, org.jdesktop.beansbinding.BeanProperty.create("text"), "grad");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 334;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        jPanel2.add(grad, gridBagConstraints);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(150, 18));
        jLabel6.setMinimumSize(new java.awt.Dimension(150, 18));
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 10);
        jPanel2.add(jLabel6, gridBagConstraints);

        naselje.setMargin(new java.awt.Insets(2, 2, 2, 2));
        naselje.setName("naselje"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${info.naselje}"), naselje, org.jdesktop.beansbinding.BeanProperty.create("text"), "naselje");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 334;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        jPanel2.add(naselje, gridBagConstraints);

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(266, 50));

        radnoVrijeme.setColumns(20);
        radnoVrijeme.setRows(5);
        radnoVrijeme.setMargin(new java.awt.Insets(2, 2, 2, 2));
        radnoVrijeme.setName("radnoVrijeme"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${info.radnoVrijeme}"), radnoVrijeme, org.jdesktop.beansbinding.BeanProperty.create("text"), "radnoVrijeme");
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(radnoVrijeme);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 322;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 10);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jPanel6.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addTab(resourceMap.getString("jPanel6.TabConstraints.tabTitle"), jPanel6); // NOI18N

        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 0, 2), javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel5.border.insideBorder.title")))); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 18));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 18));
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 10);
        jPanel5.add(jLabel1, gridBagConstraints);

        nazivLokacije.setMargin(new java.awt.Insets(2, 2, 2, 2));
        nazivLokacije.setMinimumSize(new java.awt.Dimension(14, 30));
        nazivLokacije.setName("nazivLokacije"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${info.naziv}"), nazivLokacije, org.jdesktop.beansbinding.BeanProperty.create("text"), "naziv");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jPanel5.add(nazivLokacije, gridBagConstraints);

        oznakaUredaja.setMargin(new java.awt.Insets(2, 2, 2, 2));
        oznakaUredaja.setMinimumSize(new java.awt.Dimension(14, 30));
        oznakaUredaja.setName("oznakaUredaja"); // NOI18N
        oznakaUredaja.setPreferredSize(new java.awt.Dimension(100, 32));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${info.oznakaUredaja}"), oznakaUredaja, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 10);
        jPanel5.add(oznakaUredaja, gridBagConstraints);

        nazivLokacije1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        nazivLokacije1.setName("nazivLokacije1"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${info.oibTvrtke}"), nazivLokacije1, org.jdesktop.beansbinding.BeanProperty.create("text"), "oib");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        jPanel5.add(nazivLokacije1, gridBagConstraints);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(150, 18));
        jLabel8.setMinimumSize(new java.awt.Dimension(150, 18));
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 10);
        jPanel5.add(jLabel8, gridBagConstraints);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(150, 18));
        jLabel9.setMinimumSize(new java.awt.Dimension(150, 18));
        jLabel9.setName("jLabel9"); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 10, 10);
        jPanel5.add(jLabel9, gridBagConstraints);

        datumPromjene.setMargin(new java.awt.Insets(2, 2, 2, 2));
        datumPromjene.setName("datumPromjene"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${info.datumPromjene}"), datumPromjene, org.jdesktop.beansbinding.BeanProperty.create("text_ON_FOCUS_LOST"));
        binding.setConverter(getDateConverter());
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 10);
        jPanel5.add(datumPromjene, gridBagConstraints);

        jPanel7.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addTab(resourceMap.getString("jPanel7.TabConstraints.tabTitle"), jPanel7); // NOI18N

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void Zatvori() {
        try {
            setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(IzmjenaPoslovnogProstora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Action
    public Task Fiskaliziraj() {
        return new FiskalizirajTask(Pro3App.getApplication());
    }

    private class FiskalizirajTask extends org.jdesktop.application.Task<Object, Void> {
        FiskalizirajTask(org.jdesktop.application.Application app) {
            super(app);
        }
        
        @Override protected Object doInBackground() {
            try {
                LocationInfo info = IzmjenaPoslovnogProstora.this.info;
                
                getApplication().getContext().getLocalStorage().save(info, "location.xml");
                setMessage("Lokacija je uspješno izmjenjena");
                Thread.sleep(1000);
                
                KeyInfo keyInfo = IzborCertifikata.loadKeyInfo();
                if(keyInfo != null && keyInfo.isFiskalizacijaAktivirana())
                {
                    setMessage("Povezivanje sa servisima porezne uprave");
                    setProgress(10);
                    Thread.sleep(1000);   

                    FinaClient.FiskalizacijaService service = new FinaClient.FiskalizacijaService();
                    
                    setMessage("Priprema digitalnih potpisa");
                    setProgress(20);
                    Thread.sleep(500);   

                    service.setHandlerResolver(new HandlerResolver() {

                        @Override
                        public List<Handler> getHandlerChain(PortInfo portInfo) {
                            List<Handler> handlers = new ArrayList<Handler>();
                            try {
                                KeyInfo info = IzborCertifikata.loadKeyInfo();

                                if(info != null)
                                {
                                    handlers.add(new SecureSoapHandler(info.getPath(), String.valueOf(info.getPassword()), String.valueOf(info.getPassword())));
                                }
                            } catch (Exception ex) {
                                Logger.getLogger(IzmjenaPoslovnogProstora.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            return handlers;
                        }
                    });

                    setMessage("Pripremam zaglavlje poruke");
                    setProgress(30);
                    Thread.sleep(500);   

                    FiskalizacijaPortType port = service.getFiskalizacijaPortType();
                    
                    if(General.isFiskalizacijaProdukcija())
                    {
                        BindingProvider bp = (BindingProvider) port;
                        Map<String, Object> context = bp.getRequestContext();
                        context.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "https://cis.porezna-uprava.hr:8449/FiskalizacijaService");
                    }
                    
                    PoslovniProstorZahtjev zahtjev = new PoslovniProstorZahtjev();

                    SimpleDateFormat sf = new SimpleDateFormat("dd.MM.yyyy'T'HH:mm:ss");

                    ZaglavljeType zaglavlje = new ZaglavljeType();
                    zaglavlje.setIdPoruke(UUID.randomUUID().toString());
                    zaglavlje.setDatumVrijeme(sf.format(Calendar.getInstance().getTime()));
                    zahtjev.setZaglavlje(zaglavlje);

                    setMessage("Pripremam opće podatke o poslovnom prostoru");
                    setProgress(40);
                    Thread.sleep(500);   

                    PoslovniProstorType prostor = new PoslovniProstorType();
                    prostor.setOib(info.getOibTvrtke());
                    prostor.setOznPoslProstora(info.getNaziv());

                    setMessage("Pripremam adresu poslovnog prostora");
                    setProgress(50);
                    Thread.sleep(500);   

                    AdresniPodatakType adresniPodatak = new AdresniPodatakType();
                    AdresaType adresa = new AdresaType();
                    adresa.setUlica(info.getUlica());
                    adresa.setKucniBroj(info.getBroj());
                    
                    if(!info.getDodatakBroju().isEmpty())
                    {
                        adresa.setKucniBrojDodatak(info.getDodatakBroju());
                    }
                    
                    adresa.setBrojPoste(info.getPostanskiBroj());
                    adresa.setNaselje(info.getNaselje());
                    adresa.setOpcina(info.getGrad());
                    adresniPodatak.setAdresa(adresa);
                    prostor.setAdresniPodatak(adresniPodatak);

                    setMessage("Pripremam podatke o radnom vremenu");
                    setProgress(60);
                    Thread.sleep(500);   

                    SimpleDateFormat shortSf = new SimpleDateFormat("dd.MM.yyyy");
                    prostor.setDatumPocetkaPrimjene(shortSf.format(info.getDatumPromjene()));
                    prostor.setRadnoVrijeme(info.getRadnoVrijeme());

                    setMessage("Pripremam poruku za slanje prema servisima");
                    setProgress(70);
                    Thread.sleep(500);

                    zahtjev.setPoslovniProstor(prostor);

                    setMessage("Slanje poruke prema servisima");
                    setProgress(80);
                    Thread.sleep(500);

                    PoslovniProstorOdgovor odgovor = port.poslovniProstor(zahtjev);

                    setMessage("Obrađujem odgovor servisa");
                    setProgress(90);
                    Thread.sleep(500);

                    if(odgovor.getGreske() == null)
                    {
                        setMessage("Poruka o promjeni poslovnog prostora je uspješno poslana");
                    }
                    else
                    {
                        setMessage("IZNIMKA: " + odgovor.getGreske().getGreska().get(0).getPorukaGreske());
                    }

                    setProgress(100);
                    Thread.sleep(1000);   
                }
                
                return null;
            } catch (Exception ex) {
                Logger.getLogger(IzmjenaPoslovnogProstora.class.getName()).log(Level.SEVERE, null, ex);
                setMessage("IZNIMKA: " + ex.getMessage());
                return null;
            }
        }
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktivirajPDV;
    private javax.swing.JButton cmdSpremi;
    private javax.swing.JButton cmdZatvori;
    private javax.swing.JTextField datumPromjene;
    private javax.swing.JTextField dodatakKucnomBroju;
    private javax.swing.JTextField grad;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField kucniBroj;
    private javax.swing.JTextField naselje;
    private javax.swing.JTextField nazivLokacije;
    private javax.swing.JTextField nazivLokacije1;
    private javax.swing.JTextField oznakaUredaja;
    private javax.swing.JTextField postanskiBroj;
    private javax.swing.JTextArea radnoVrijeme;
    private javax.swing.JTextField ulica;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
