// Pro3x Community project
// Copyright (C) 2009  Aleksandar Zgonjan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, http://www.gnu.org/licenses/gpl.html

package Acosoft.Processing.Components;

import java.awt.Color;
import java.awt.Cursor;
import java.net.URI;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author nonstop
 */
public class Pro3xRenderRSS extends javax.swing.JPanel
{
    private DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
    private String rssLokacija = null;
    private Color defaultColor;

    /** Creates new form Pro3xRenderRSS */
    public Pro3xRenderRSS(Pro3xRssItem item)
    {
        initComponents();
        Load(item);
        defaultColor = rssNaslov.getForeground();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rssDatum = new javax.swing.JLabel();
        rssNaslov = new javax.swing.JLabel();
        rssOpis = new javax.swing.JTextArea();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getResourceMap(Pro3xRenderRSS.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setMaximumSize(new java.awt.Dimension(32767, 200));
        setMinimumSize(new java.awt.Dimension(0, 200));
        setName("Form"); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(329, 200));

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);

        rssDatum.setText(resourceMap.getString("rssDatum.text")); // NOI18N
        rssDatum.setName("rssDatum"); // NOI18N

        rssNaslov.setFont(rssNaslov.getFont().deriveFont((float)24));
        rssNaslov.setIcon(resourceMap.getIcon("rssNaslov.icon")); // NOI18N
        rssNaslov.setText(resourceMap.getString("rssNaslov.text")); // NOI18N
        rssNaslov.setName("rssNaslov"); // NOI18N
        rssNaslov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rssNaslovMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rssNaslovMouseExit(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rssNaslov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(rssDatum)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rssNaslov)
                .addComponent(rssDatum))
        );

        rssOpis.setColumns(20);
        rssOpis.setEditable(false);
        rssOpis.setLineWrap(true);
        rssOpis.setRows(5);
        rssOpis.setWrapStyleWord(true);
        rssOpis.setMargin(new java.awt.Insets(5, 5, 5, 5));
        rssOpis.setMinimumSize(new java.awt.Dimension(0, 0));
        rssOpis.setName("rssOpis"); // NOI18N
        rssOpis.setPreferredSize(new java.awt.Dimension(110, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rssOpis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rssOpis, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void handleClick(java.awt.event.MouseEvent evt)//GEN-FIRST:event_handleClick
    {//GEN-HEADEREND:event_handleClick
        if(java.awt.Desktop.isDesktopSupported())
            try { java.awt.Desktop.getDesktop().browse(new URI(rssLokacija)); }
            catch(Exception ex)
            {
                //TODO: obradi iznimke
            }
    }//GEN-LAST:event_handleClick

    private void rssNaslovMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_rssNaslovMouseEntered
    {//GEN-HEADEREND:event_rssNaslovMouseEntered
        rssNaslov.setCursor(new Cursor(Cursor.HAND_CURSOR));
        rssNaslov.setForeground(Color.gray);
    }//GEN-LAST:event_rssNaslovMouseEntered

    private void rssNaslovMouseExit(java.awt.event.MouseEvent evt)//GEN-FIRST:event_rssNaslovMouseExit
    {//GEN-HEADEREND:event_rssNaslovMouseExit
        rssNaslov.setForeground(defaultColor);
    }//GEN-LAST:event_rssNaslovMouseExit

    public void Load(Pro3xRssItem item)
    {
        this.rssDatum.setText(df.format(item.getDatum()));
        this.rssNaslov.setText(item.getNaslov());
        this.rssOpis.setText(item.getOpis());
        this.rssLokacija = item.getLokacija();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rssDatum;
    private javax.swing.JLabel rssNaslov;
    private javax.swing.JTextArea rssOpis;
    // End of variables declaration//GEN-END:variables

}
