/*
 * Pro3x Community project
 * Copyright (C) 2009  Aleksandar Zgonjan
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, http://www.gnu.org/licenses/gpl.html
 * and open the template in the editor.
 */

/*
 * PregledKalkulacije.java
 *
 * Created on 17.11.2009., 20:53:37
 */

package Pro3x.Kalkulacije;

import Pro3x.Code.Akcija;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nonstop
 */
public class PregledKalkulacije extends javax.swing.JInternalFrame {

    IzmjenaKalkulacije izmjena;

    public PregledKalkulacije()
    {
        this(null);
    }

    /** Creates new form PregledKalkulacije */


    public PregledKalkulacije(String kalkulacija)
    {
        initComponents();

        if(kalkulacija == null)
            izmjena = new IzmjenaKalkulacije();
        else
        {
            izmjena = new IzmjenaKalkulacije(kalkulacija);
            setTitle("Izmjena kalkulacije: " + izmjena.getKalkulacija().getOznakaDokumenta());
        }

        this.getContentPane().add(izmjena);
        pack();
        
        izmjena.setZatvori(new Akcija()
        {
            public void Izvrsi()
            {
                try
                {
                    setClosed(true);
                }
                catch (PropertyVetoException ex)
                {
                    Logger.getLogger(PregledKalkulacije.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getResourceMap(PregledKalkulacije.class);
        setTitle(resourceMap.getString("maloprodajna-kalkulacija-pregled-v2.title")); // NOI18N
        setName("maloprodajna-kalkulacija-pregled-v2"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosing
    {//GEN-HEADEREND:event_formInternalFrameClosing
        izmjena.UkloniSlusatelja();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
