/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NapredniPregledStanjaSkladista.java
 *
 * Created on 07.04.2013., 11:36:44
 */
package Pro3x.View;

import Acosoft.Processing.Components.NumberCellRenderer;
import Acosoft.Processing.Pro3App;
import Acosoft.Processing.Pro3Postavke;
import Acosoft.Processing.Pro3View;
import Pro3x.Code.ReportingServices;
import Pro3x.View.Models.SimpleModelStanjaSkladista;
import Pro3x.View.Models.StanjeArtikla;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JasperPrint;
import org.jdesktop.application.Action;

/**
 *
 * @author aco
 */
public class NapredniPregledStanjaSkladista extends javax.swing.JInternalFrame {

    private SimpleModelStanjaSkladista model;
    
    /** Creates new form NapredniPregledStanjaSkladista */
    public NapredniPregledStanjaSkladista(SimpleModelStanjaSkladista model) {
        
        this.model = model;
        
        initComponents();
        
        grid.setDefaultRenderer(Double.class, new NumberCellRenderer());
        grid.getColumnModel().getColumn(1).setCellRenderer(new NumberCellRenderer(false, true, 3, 3));
    }

    public SimpleModelStanjaSkladista getModel() {
        return model;
    }

    public void setModel(SimpleModelStanjaSkladista model) {
        this.model = model;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grid = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getResourceMap(NapredniPregledStanjaSkladista.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 5, 10));
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 5));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        grid.setAutoCreateRowSorter(true);
        grid.setModel(getModel());
        grid.setName("grid"); // NOI18N
        grid.setRowHeight(35);
        jScrollPane1.setViewportView(grid);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getActionMap(NapredniPregledStanjaSkladista.class, this);
        jButton2.setAction(actionMap.get("AkcijaPregledKartice")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel3.add(jButton2);

        jButton4.setAction(actionMap.get("IspisStanja")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel3.add(jButton4);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("jSeparator1"); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(6, 30));
        jPanel3.add(jSeparator1);

        jButton3.setAction(actionMap.get("Zatvori")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel3.add(jButton3);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void Zatvori() {
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(NapredniPregledStanjaSkladista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Action
    public void OsvjeziPregled() {
        
    }

    @Action
    public void AkcijaPregledKartice() {
        SimpleModelStanjaSkladista model = (SimpleModelStanjaSkladista) grid.getModel();
        int index = grid.convertRowIndexToModel(grid.getSelectedRow());

        Pro3View main = (Pro3View) Pro3App.getApplication().getMainView();
        main.Show(new PregledKartice(model.getArtikal(index)));
    }

    @Action
    public void IspisStanja() throws Exception {
        
        HashMap params = new HashMap();
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        
        params.put("datum", sdf.format(Calendar.getInstance().getTime()));
        params.put("logo", Pro3Postavke.getLogoStream());
        params.put("zaglavlje", Pro3Postavke.getInfo().getZaglavlje());
        
        SimpleModelStanjaSkladista model = (SimpleModelStanjaSkladista) grid.getModel();
        List<StanjeArtikla> data = model.getStanje();
        
        JasperPrint report = ReportingServices.LoadReport(NapredniPregledStanjaSkladista.class, "reports/StanjeSkladista.jasper", params, data);
        ReportingServices.ShowReport(report, "Stanje skladišta", "stanje-skladista-2013-04-v1");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grid;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
