/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Pro3x.View;

import Acosoft.Processing.Pro3App;
import java.beans.PropertyVetoException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jdesktop.application.Application;

/**
 *
 * @author aco
 */
public class PovratGotovine extends javax.swing.JInternalFrame {

    private double iznosRacuna;
    private double iznosUplate;
    private double ukupno;
    private String valuta =  "kn";
    private NumberFormat nf;

    public String getValuta() {
        return valuta;
    }

    public void setValuta(String valuta) 
    {
        this.valuta = valuta;
    }

    public double getIznosRacuna() 
    {
        return iznosRacuna;
    }

    public void setIznosRacuna(double iznosRacuna) 
    {
        this.iznosRacuna = iznosRacuna;
    }

    public double getIznosUplate() 
    {
        return iznosUplate;
    }

    public void setIznosUplate(double iznosUplate) 
    {
        this.iznosUplate = iznosUplate;
        infoUplate.setText(nf.format(iznosUplate) + " " +  valuta);
        infoUplate.selectAll();
        
        setUkupno(iznosUplate - iznosRacuna);
    }
    
    public double getUkupno() 
    {
        return ukupno;
    }

    public void setUkupno(double ukupno) 
    {
        this.ukupno = ukupno;
        infoUkupno.setText(nf.format(ukupno) + " " + valuta);
    }

    public PovratGotovine(double iznosRacuna) 
    {
        this(iznosRacuna, "kn");
    }
    
    /**
     * Creates new form PovratGotovine
     */
    public PovratGotovine(double iznosRacuna, String valuta) 
    {
        this.iznosRacuna = iznosRacuna;
        this.iznosUplate = 0;
        this.ukupno = 0;
        this.valuta = valuta;

        nf = NumberFormat.getInstance();
        nf.setMinimumFractionDigits(2);
        nf.setMaximumFractionDigits(2);
        
        initComponents();
        
        infoRacun.setText(nf.format(iznosRacuna) + " " + valuta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        infoUkupno = new javax.swing.JLabel();
        cmdZatvori = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        infoRacun = new javax.swing.JTextField();
        infoUplate = new javax.swing.JTextField();
        cmdIzracunaj = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Povrat gotovine");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ukupno za vratiti"));

        infoUkupno.setFont(infoUkupno.getFont().deriveFont((float)32));
        infoUkupno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoUkupno.setText("0,00 kn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoUkupno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoUkupno, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );

        cmdZatvori.setText("Zatvori");
        cmdZatvori.setNextFocusableComponent(infoUplate);
        cmdZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdZatvoriActionPerformed(evt);
            }
        });

        jLabel2.setText("Iznos uplate");

        jLabel3.setText("Iznos računa");

        infoRacun.setEditable(false);
        infoRacun.setFont(infoRacun.getFont().deriveFont((float)16));
        infoRacun.setText("0,00 kn");
        infoRacun.setNextFocusableComponent(cmdIzracunaj);

        infoUplate.setFont(infoUplate.getFont().deriveFont((float)16));
        infoUplate.setText("0,00 kn");
        infoUplate.setNextFocusableComponent(infoRacun);
        infoUplate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IznosUplateFocused(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IznosUplateBlur(evt);
            }
        });

        cmdIzracunaj.setText("Izračunaj");
        cmdIzracunaj.setNextFocusableComponent(cmdZatvori);
        cmdIzracunaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIzracunajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmdIzracunaj, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(infoUplate, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(infoRacun, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(infoUplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(infoRacun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdZatvori)
                    .addComponent(cmdIzracunaj))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IznosUplateFocused(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IznosUplateFocused
        this.getRootPane().setDefaultButton(cmdIzracunaj);
        infoUplate.selectAll();
    }//GEN-LAST:event_IznosUplateFocused

    private void IznosUplateBlur(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IznosUplateBlur

        this.getRootPane().setDefaultButton(cmdZatvori);
    }//GEN-LAST:event_IznosUplateBlur

    private void cmdZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdZatvoriActionPerformed
        try 
        {
            setClosed(true);
        } 
        catch (PropertyVetoException ex) 
        {
            Logger.getLogger(PovratGotovine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdZatvoriActionPerformed

    private void cmdIzracunajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIzracunajActionPerformed
        
        Pro3App app = Pro3App.getApplication();
        
        try 
        {
            double iznos = nf.parse(infoUplate.getText()).doubleValue();
            setIznosUplate(iznos);
        } 
        catch (ParseException ex) 
        {
            Logger.getLogger(PovratGotovine.class.getName()).log(Level.SEVERE, null, ex);
            setIznosUplate(0);
        }
    }//GEN-LAST:event_cmdIzracunajActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdIzracunaj;
    private javax.swing.JButton cmdZatvori;
    private javax.swing.JTextField infoRacun;
    private javax.swing.JLabel infoUkupno;
    private javax.swing.JTextField infoUplate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
