/*
 * Pro3x Community project
 * Copyright (C) 2009  Aleksandar Zgonjan
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, http://www.gnu.org/licenses/gpl.html
 * and open the template in the editor.
 */

/*
 * PredlozakBiljeskeRacuna.java
 *
 * Created on 2009.07.25, 14:55:56
 */

package Pro3x.View;

import Acosoft.Processing.Components.TemplateInfo;
import Acosoft.Processing.DataBox.Template;
import Pro3x.BasicView;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.filechooser.FileFilter;
import javax.swing.plaf.basic.ComboPopup;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import org.jdesktop.beansbinding.Converter;
import org.jvnet.substance.api.renderers.SubstanceDefaultComboBoxRenderer;
import org.jvnet.substance.api.renderers.SubstanceDefaultListCellRenderer;

/**
 *
 * @author nonstop
 */
public class PredlozakBiljeskeRacuna extends BasicView {
    
    public static final String DodatneInformacije = "dodatne informacije";
    public static final String NapomenaRacuna = "napomena";
    public static final String NazivTvrtke = "naziv tvrtke";
    public static final String OznakaRacuna = "oznaka računa";
    public static final String ZiroRacun = "žiro račun";

    private boolean changed = false;
    private List<TemplateInfo> templateList;
    private Converter<String, TemplateInfo> converter;

    /** Creates new form PredlozakBiljeskeRacuna */
    public PredlozakBiljeskeRacuna() {
        templateList = new ArrayList<TemplateInfo>();
        
        templateList.add(new TemplateInfo("reports/invoice-a4.jasper", "A4"));
        templateList.add(new TemplateInfo("reports/invoice-v1.jasper", "POS"));
        
        converter = new Converter<String, TemplateInfo>() {

            @Override
            public TemplateInfo convertForward(String value) {
                
                for (TemplateInfo info : templateList) {
                    if(info.getPath().equals(value))
                        return info;
                }
                
                return null;
            }

            @Override
            public String convertReverse(TemplateInfo value) {
                return value.getPath();
            }
        };
        
        initComponents();
        comTypes.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPopupMenu1 = new javax.swing.JPopupMenu();
        varOznakaRacuna = new javax.swing.JMenuItem();
        varNapomenaRacuna = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        varZiroRacun = new javax.swing.JMenuItem();
        varDodatneInformacije = new javax.swing.JMenuItem();
        varNazivTvrtke = new javax.swing.JMenuItem();
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getResourceMap(PredlozakBiljeskeRacuna.class);
        queryTemplates = java.beans.Beans.isDesignTime() ? null : getProManager().createQuery(resourceMap.getString("queryTemplates.query")); // NOI18N
        templates = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(new java.util.LinkedList(queryTemplates.getResultList()));
        queryStope = java.beans.Beans.isDesignTime() ? null : getProManager().createQuery(resourceMap.getString("queryStope.query")); // NOI18N
        stopeList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : queryStope.getResultList();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        izborPredloska = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        odgodaPlacanja = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        putanjaPredloska = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        comTypes = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();

        jPopupMenu1.setName("jPopupMenu1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getActionMap(PredlozakBiljeskeRacuna.class, this);
        varOznakaRacuna.setAction(actionMap.get("DodajOznakuRacuna")); // NOI18N
        varOznakaRacuna.setText(resourceMap.getString("varOznakaRacuna.text")); // NOI18N
        varOznakaRacuna.setToolTipText(resourceMap.getString("varOznakaRacuna.toolTipText")); // NOI18N
        varOznakaRacuna.setName("varOznakaRacuna"); // NOI18N
        jPopupMenu1.add(varOznakaRacuna);

        varNapomenaRacuna.setAction(actionMap.get("DodajNapomenuRacuna")); // NOI18N
        varNapomenaRacuna.setText(resourceMap.getString("varNapomenaRacuna.text")); // NOI18N
        varNapomenaRacuna.setToolTipText(resourceMap.getString("varNapomenaRacuna.toolTipText")); // NOI18N
        varNapomenaRacuna.setName("varNapomenaRacuna"); // NOI18N
        jPopupMenu1.add(varNapomenaRacuna);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jPopupMenu1.add(jSeparator2);

        varZiroRacun.setAction(actionMap.get("DodajZiroRacun")); // NOI18N
        varZiroRacun.setText(resourceMap.getString("varZiroRacun.text")); // NOI18N
        varZiroRacun.setName("varZiroRacun"); // NOI18N
        jPopupMenu1.add(varZiroRacun);

        varDodatneInformacije.setAction(actionMap.get("DodajDodatneInformacije")); // NOI18N
        varDodatneInformacije.setText(resourceMap.getString("varDodatneInformacije.text")); // NOI18N
        varDodatneInformacije.setName("varDodatneInformacije"); // NOI18N
        jPopupMenu1.add(varDodatneInformacije);

        varNazivTvrtke.setAction(actionMap.get("DodajNazivTvrtke")); // NOI18N
        varNazivTvrtke.setText(resourceMap.getString("varNazivTvrtke.text")); // NOI18N
        varNazivTvrtke.setName("varNazivTvrtke"); // NOI18N
        jPopupMenu1.add(varNazivTvrtke);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(resourceMap.getString("predlozak-biljeski-racuna")); // NOI18N
        setName("predlozak-biljeski-racuna-v5"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                ProvjeraIzmjenaPrijeZatvaranja(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton2.setAction(actionMap.get("SpremiPromjene")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setMaximumSize(new java.awt.Dimension(90, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(90, 30));
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel3.add(jButton2);

        jButton1.setAction(actionMap.get("ZatvoriPredloske")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(90, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(90, 30));
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel3.add(jButton1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        izborPredloska.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 0, 5));
        izborPredloska.setAlignmentX(1.0F);
        izborPredloska.setMinimumSize(new java.awt.Dimension(500, 250));
        izborPredloska.setName("izborPredloska"); // NOI18N
        izborPredloska.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 0);
        izborPredloska.add(jLabel1, gridBagConstraints);

        jTextField1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jTextField1.setName("jTextField1"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, comTypes, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.oznakaRacuna}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        izborPredloska.add(jTextField1, gridBagConstraints);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 0);
        izborPredloska.add(jLabel2, gridBagConstraints);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        editor.setColumns(20);
        editor.setLineWrap(true);
        editor.setRows(5);
        editor.setComponentPopupMenu(jPopupMenu1);
        editor.setMargin(new java.awt.Insets(2, 2, 2, 2));
        editor.setName("editor"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, comTypes, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.format}"), editor, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        editor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IzmjenjenPredlozak(evt);
            }
        });
        jScrollPane1.setViewportView(editor);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        izborPredloska.add(jScrollPane1, gridBagConstraints);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 0);
        izborPredloska.add(jLabel4, gridBagConstraints);

        odgodaPlacanja.setMargin(new java.awt.Insets(2, 2, 2, 2));
        odgodaPlacanja.setName("odgodaPlacanja"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, comTypes, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.rokPlacanja}"), odgodaPlacanja, org.jdesktop.beansbinding.BeanProperty.create("text_ON_FOCUS_LOST"), "rok-placanja");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        izborPredloska.add(odgodaPlacanja, gridBagConstraints);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 10);
        izborPredloska.add(jLabel5, gridBagConstraints);

        putanjaPredloska.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        putanjaPredloska.setMinimumSize(new java.awt.Dimension(80, 30));
        putanjaPredloska.setName(""); // NOI18N
        putanjaPredloska.setPreferredSize(new java.awt.Dimension(80, 30));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${templates}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, putanjaPredloska);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, comTypes, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.predlozak}"), putanjaPredloska, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        binding.setConverter(getConverter());
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        izborPredloska.add(putanjaPredloska, gridBagConstraints);

        jSplitPane1.setRightComponent(izborPredloska);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 2));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        comTypes.setFixedCellHeight(30);
        comTypes.setName("comTypes"); // NOI18N

        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, templates, comTypes);
        jListBinding.setDetailBinding(org.jdesktop.beansbinding.ELProperty.create("${tip}"));
        bindingGroup.addBinding(jListBinding);

        jScrollPane2.setViewportView(comTypes);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 5, 5));
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel2.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setLeftComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IzmjenjenPredlozak(java.awt.event.KeyEvent evt)//GEN-FIRST:event_IzmjenjenPredlozak
    {//GEN-HEADEREND:event_IzmjenjenPredlozak
        changed = true;
    }//GEN-LAST:event_IzmjenjenPredlozak

    private void ProvjeraIzmjenaPrijeZatvaranja(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_ProvjeraIzmjenaPrijeZatvaranja
    {//GEN-HEADEREND:event_ProvjeraIzmjenaPrijeZatvaranja
        if(changed)
        {
            int result = JOptionPane.showConfirmDialog(this, "Želite li spremiti promjene?",
                    "Upozorenje", JOptionPane.YES_NO_OPTION);

            if(result == JOptionPane.YES_OPTION)
                SpremiPromjene();
        }
    }//GEN-LAST:event_ProvjeraIzmjenaPrijeZatvaranja

    public List<TemplateInfo> getTemplates()
    {
        return templateList;
    }
    
    public Converter<String, TemplateInfo> getConverter()
    {
        return converter;
    }
    
    @Action
    public void DodajZiroRacun()
    {
        editor.insert("{" + ZiroRacun + "}", editor.getSelectionStart());
    }

    @Action
    public void DodajOznakuRacuna()
    {
        editor.insert("{" + OznakaRacuna + "}", editor.getSelectionStart());
    }

    @Action
    public void DodajDodatneInformacije()
    {
        editor.insert("{" + DodatneInformacije + "}", editor.getSelectionStart());
    }

    @Action
    public void DodajNazivTvrtke()
    {
        editor.insert("{" + NazivTvrtke + "}", editor.getSelectionStart());
    }

        @Action
    public void DodajNapomenuRacuna()
    {
        editor.insert("{" + NapomenaRacuna + "}", editor.getSelectionStart());
    }

    private int count = 1;

    @Action
    public void DodajNoviTemplate()
    {
        Template temp = new Template();
        temp.setOznaka(UUID.randomUUID().toString());
        temp.setOznakaRacuna(String.valueOf(count) + ". template");
        temp.setTip("Nije plaćen");

        templates.add(temp);
        count++;

        getProManager().getTransaction().begin();
        getProManager().persist(temp);
        getProManager().getTransaction().commit();
    }

    @Action
    public Task SpremiPromjene()
    {
        return new SpremiPromjeneTask(org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class));
    }

    private class SpremiPromjeneTask extends org.jdesktop.application.Task<Object, Void> {
        SpremiPromjeneTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to SpremiPromjeneTask fields, here.
            super(app);
        }
        @Override protected Object doInBackground()
        {
            setMessage("Spremam predloške bilješki računa.");
            getProManager().getTransaction().begin();

            for(Template x : templates)
                getProManager().persist(x);

            getProManager().getTransaction().commit();

            return true;
        }
        @Override protected void succeeded(Object result) {
            setMessage("Predlošci bilješki računa su uspješno spremljeni.");
            changed = !(Boolean)result;
        }
    }

    @Action
    public void ZatvoriPredloske()
    {
        try
        {
            setClosed(true);
        }
        catch (PropertyVetoException ex)
        {
            Logger.getLogger(PredlozakBiljeskeRacuna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList comTypes;
    private javax.swing.JTextArea editor;
    private javax.swing.JPanel izborPredloska;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField odgodaPlacanja;
    private javax.swing.JComboBox putanjaPredloska;
    private javax.persistence.Query queryStope;
    private javax.persistence.Query queryTemplates;
    private java.util.List<Acosoft.Processing.DataBox.PoreznaStopa> stopeList;
    private java.util.List<Acosoft.Processing.DataBox.Template> templates;
    private javax.swing.JMenuItem varDodatneInformacije;
    private javax.swing.JMenuItem varNapomenaRacuna;
    private javax.swing.JMenuItem varNazivTvrtke;
    private javax.swing.JMenuItem varOznakaRacuna;
    private javax.swing.JMenuItem varZiroRacun;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
