/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PregledGrupaArtikala.java
 *
 * Created on 06.02.2013., 20:47:11
 */
package Pro3x.View;

import Acosoft.Processing.Components.Tasks;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import org.jdesktop.application.Action;

/**
 *
 * @author aco
 */
public class PregledEntiteta extends JInternalFrame {

    private SimpleModel model;
    
    /** Creates new form PregledGrupaArtikala */
    public PregledEntiteta(SimpleModel model) {
        this.model = model;        
        initComponents();
        
        addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                if(PregledEntiteta.this.model.isChanged() && 
                        JOptionPane.showConfirmDialog(PregledEntiteta.this, "Želite li spremiti promjene?", "Upozorenje", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION)
                {
                    PregledEntiteta.this.Spremi();
                }
            }
        });
        
        grid.setModel(model);
        model.refresh();
    }
    
    public void setRenderer(Class<?> columnClass, TableCellRenderer renderer)
    {
        grid.setDefaultRenderer(columnClass, renderer);
    }
    
    public void setEditor(Class<?> columnClass, TableCellEditor editor)
    {
        grid.setDefaultEditor(columnClass, editor);
    }
    
    public void setTableTitle(String tableTitle)
    {
        title.setText(tableTitle);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmdOsvjezi = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        cmdDodaj = new javax.swing.JButton();
        cmdIzmjeni = new javax.swing.JButton();
        cmdIzbrisi = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cmdSpremi = new javax.swing.JButton();
        cmdZatvori = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grid = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pregled grupa artikala"); // NOI18N
        setName("pregled-grupa-artikala-v6"); // NOI18N

        title.setFont(new java.awt.Font("Ubuntu", 0, 24));
        title.setText("Uređivanje grupa artikala"); // NOI18N
        title.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 5, 10));
        title.setName("title"); // NOI18N
        getContentPane().add(title, java.awt.BorderLayout.PAGE_START);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getActionMap(PregledEntiteta.class, this);
        cmdOsvjezi.setAction(actionMap.get("Osvjezi")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getResourceMap(PregledEntiteta.class);
        cmdOsvjezi.setText(resourceMap.getString("cmdOsvjezi.text")); // NOI18N
        cmdOsvjezi.setMaximumSize(new java.awt.Dimension(90, 30));
        cmdOsvjezi.setMinimumSize(new java.awt.Dimension(90, 30));
        cmdOsvjezi.setName("cmdOsvjezi"); // NOI18N
        cmdOsvjezi.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(cmdOsvjezi);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setName("jSeparator2"); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(6, 30));
        jPanel1.add(jSeparator2);

        cmdDodaj.setAction(actionMap.get("Dodaj")); // NOI18N
        cmdDodaj.setText(resourceMap.getString("cmdDodaj.text")); // NOI18N
        cmdDodaj.setMaximumSize(new java.awt.Dimension(90, 30));
        cmdDodaj.setMinimumSize(new java.awt.Dimension(90, 30));
        cmdDodaj.setName("cmdDodaj"); // NOI18N
        cmdDodaj.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(cmdDodaj);

        cmdIzmjeni.setAction(actionMap.get("Izmjeni")); // NOI18N
        cmdIzmjeni.setText(resourceMap.getString("cmdIzmjeni.text")); // NOI18N
        cmdIzmjeni.setMaximumSize(new java.awt.Dimension(90, 30));
        cmdIzmjeni.setMinimumSize(new java.awt.Dimension(90, 30));
        cmdIzmjeni.setName("cmdIzmjeni"); // NOI18N
        cmdIzmjeni.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(cmdIzmjeni);

        cmdIzbrisi.setAction(actionMap.get("Izbrisi")); // NOI18N
        cmdIzbrisi.setText(resourceMap.getString("cmdIzbrisi.text")); // NOI18N
        cmdIzbrisi.setMaximumSize(new java.awt.Dimension(90, 30));
        cmdIzbrisi.setMinimumSize(new java.awt.Dimension(90, 30));
        cmdIzbrisi.setName("cmdIzbrisi"); // NOI18N
        cmdIzbrisi.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(cmdIzbrisi);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("jSeparator1"); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(6, 30));
        jPanel1.add(jSeparator1);

        cmdSpremi.setAction(actionMap.get("Spremi")); // NOI18N
        cmdSpremi.setText(resourceMap.getString("cmdSpremi.text")); // NOI18N
        cmdSpremi.setMaximumSize(new java.awt.Dimension(90, 30));
        cmdSpremi.setMinimumSize(new java.awt.Dimension(90, 30));
        cmdSpremi.setName("cmdSpremi"); // NOI18N
        cmdSpremi.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(cmdSpremi);

        cmdZatvori.setAction(actionMap.get("Zatvori")); // NOI18N
        cmdZatvori.setText(resourceMap.getString("cmdZatvori.text")); // NOI18N
        cmdZatvori.setMaximumSize(new java.awt.Dimension(90, 30));
        cmdZatvori.setMinimumSize(new java.awt.Dimension(90, 30));
        cmdZatvori.setName("cmdZatvori"); // NOI18N
        cmdZatvori.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(cmdZatvori);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 5));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        grid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grid.setName("grid"); // NOI18N
        grid.setRowHeight(35);
        grid.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(grid);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void Osvjezi() {
        
        stopEditing();
        
        if(model.isChanged() && 
                JOptionPane.showConfirmDialog(this, "Želite li spremiti promjene?", "Upozorenje", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION)
        {
            Spremi();
        }
        
        model.refresh();
    }
    
    private void stopEditing()
    {
        if(grid.isEditing() == true)
        {
            grid.getCellEditor().stopCellEditing();
        }
        
    }

    @Action
    public void Dodaj() {
        model.add();
        
        int index = grid.getRowCount() - 1;
        
        grid.editCellAt(index, 0);
        grid.setRowSelectionInterval(index, index);
        
        grid.getEditorComponent().requestFocus();
    }

    @Action
    public void Izmjeni() {

        if(grid.getSelectedRowCount() == 1)
        {
            int index = grid.getSelectedRow();
            grid.editCellAt(index, 0);

            grid.getEditorComponent().requestFocus();
        }
        else
        {
            Tasks.showMessage("Izaberite red koji želite izmjeniti");
        }
    }

    @Action
    public void Izbrisi() {
        
        if(grid.getSelectedRowCount() == 1)
        {
            int index = grid.getSelectedRow();
            int modelIndex = grid.convertRowIndexToModel(index);

            model.remove(index);
        }
        else
        {
            Tasks.showMessage("Izaberite red koji želite izbrisati");
        }
    }

    @Action
    public void Spremi() {

        stopEditing();
        
        model.save();
        Tasks.showMessage("Promjene su uspješno spremljene");
    }

    @Action
    public void Zatvori() {
        try {
            stopEditing();
            
            setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(PregledEntiteta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDodaj;
    private javax.swing.JButton cmdIzbrisi;
    private javax.swing.JButton cmdIzmjeni;
    private javax.swing.JButton cmdOsvjezi;
    private javax.swing.JButton cmdSpremi;
    private javax.swing.JButton cmdZatvori;
    private javax.swing.JTable grid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
