/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditorCijenePopup.java
 *
 * Created on 2010.03.18, 23:32:48
 */

package Pro3x.Code;

import Acosoft.Processing.Components.Tasks;
import java.awt.event.ContainerAdapter;
import java.awt.event.ContainerEvent;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import org.jdesktop.application.Action;

/**
 *
 * @author Aco
 */
public class EditorCijenePopup extends javax.swing.JPanel //implements MenuElement
{
    private EditorCijene editor;
    private NumberFormat nf;
    private Double staraCijena;
    private Double novaCijena;

    /** Creates new form EditorCijenePopup */
    public EditorCijenePopup(EditorCijene editor) {

        this.editor = editor;
        this.nf = editor.getFormat();

        initComponents();
    }

    public void PromjeniCijenu(double cijena)
    {
        this.staraCijena = cijena;
        this.novaCijena = 0D;

        String prikaz = nf.format(cijena);
        prikazCijene.setText(prikaz);

        iznosPopusta.setText(nf.format(0));
        popust.setText(nf.format(0));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        prikazCijene = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        iznosPopusta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        popust = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getResourceMap(EditorCijenePopup.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        prikazCijene.setFont(resourceMap.getFont("prikazCijene.font")); // NOI18N
        prikazCijene.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prikazCijene.setText(resourceMap.getString("prikazCijene.text")); // NOI18N
        prikazCijene.setName("prikazCijene"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prikazCijene, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prikazCijene, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        iznosPopusta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        iznosPopusta.setText(resourceMap.getString("iznosPopusta.text")); // NOI18N
        iznosPopusta.setName("iznosPopusta"); // NOI18N
        iznosPopusta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NovaCijenaFocused(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                iznosPopustaFocusLost(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        popust.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        popust.setText(resourceMap.getString("popust.text")); // NOI18N
        popust.setName("popust"); // NOI18N
        popust.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                popustFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                popustFocusLost(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getActionMap(EditorCijenePopup.class, this);
        jButton1.setAction(actionMap.get("Zatvori")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("Spremi")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(popust, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(iznosPopusta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(popust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(iznosPopusta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NovaCijenaFocused(java.awt.event.FocusEvent evt)//GEN-FIRST:event_NovaCijenaFocused
    {//GEN-HEADEREND:event_NovaCijenaFocused
        iznosPopusta.selectAll();
    }//GEN-LAST:event_NovaCijenaFocused

    private void iznosPopustaFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_iznosPopustaFocusLost
    {//GEN-HEADEREND:event_iznosPopustaFocusLost
        Double vrijednost = Formatiraj(iznosPopusta);
        novaCijena = staraCijena - vrijednost;

        PromjeniCijenu();
        popust.setText(nf.format(vrijednost / (staraCijena / 100)));
    }//GEN-LAST:event_iznosPopustaFocusLost

    private void popustFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_popustFocusGained
    {//GEN-HEADEREND:event_popustFocusGained
        popust.selectAll();
    }//GEN-LAST:event_popustFocusGained

    private void popustFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_popustFocusLost
    {//GEN-HEADEREND:event_popustFocusLost
        Double popustPostotak = Formatiraj(popust);
        Double iznos = staraCijena * (popustPostotak / 100);
        novaCijena = staraCijena - iznos;

        PromjeniCijenu();
        iznosPopusta.setText(nf.format(iznos));
    }//GEN-LAST:event_popustFocusLost

    private void PromjeniCijenu()
    {
        String prikaz = nf.format(novaCijena);
        prikazCijene.setText(prikaz);
    }

    @Override
    public boolean requestFocusInWindow()
    {
        grabFocus();
        return popust.requestFocusInWindow();
    }

    private Double Formatiraj(JTextField polje)
    {
        try
        {
            Double vrijednost = nf.parse(polje.getText()).doubleValue();
            polje.setText(nf.format(vrijednost));

            return vrijednost;
        }
        catch (ParseException ex)
        {
            Logger.getLogger(EditorCijenePopup.class.getName()).log(Level.SEVERE, null, ex);
            Tasks.showMessage("Iznimka pri formatiranju prikaza. Provjerite upisane podatke.");

            return 0D;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField iznosPopusta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField popust;
    private javax.swing.JLabel prikazCijene;
    // End of variables declaration//GEN-END:variables

    @Action
    public void Zatvori()
    {
        editor.stopCellEditing();
        
        JPopupMenu pop = (JPopupMenu) getParent();
        pop.setVisible(false);
    }

    @Action
    public void Spremi()
    {
        editor.setCijena(novaCijena);
        Zatvori();
    }
}
