// Pro3x Community project
// Copyright (C) 2009  Aleksandar Zgonjan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, http://www.gnu.org/licenses/gpl.html

package Acosoft.Processing;

import Acosoft.Processing.Components.RunNoviKorisnik;
import Acosoft.Processing.DataBox.Korisnik;
import Pro3x.Persistence;
import java.beans.PropertyVetoException;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityTransaction;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;
import org.jdesktop.application.Task;

/**
 *
 * @author nonstop
 */

//TODO: dodaj podatak o broju ugovora
public class NoviKorisnik extends javax.swing.JInternalFrame {

    /** Creates new form NoviKorisnik */
    public NoviKorisnik() {
        initComponents();
        this.getRootPane().setDefaultButton(cmdSpremi);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        proManager = java.beans.Beans.isDesignTime() ? null : Persistence.createEntityManagerFactory().createEntityManager();
        jPanel4 = new javax.swing.JPanel();
        cmdSpremi = new javax.swing.JButton();
        cmdZatvori = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        maticniBroj = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nazivKorisnika = new javax.swing.JTextField();
        lokacijaKorisnika = new javax.swing.JTextField();
        adresaKorisnika = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        emailKorisnika = new javax.swing.JTextField();
        telefonKorisnika = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mobitelKorisnika = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Acosoft.Processing.Pro3App.class).getContext().getResourceMap(NoviKorisnik.class);
        setTitle(resourceMap.getString("izmjena-korisnika-v2.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(500, 450));
        setName("izmjena-korisnika-v2"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 450));

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        cmdSpremi.setText(resourceMap.getString("cmdSpremi.text")); // NOI18N
        cmdSpremi.setMaximumSize(new java.awt.Dimension(90, 30));
        cmdSpremi.setMinimumSize(new java.awt.Dimension(90, 30));
        cmdSpremi.setName("cmdSpremi"); // NOI18N
        cmdSpremi.setPreferredSize(new java.awt.Dimension(90, 30));
        cmdSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpremiNovogKorisnika(evt);
            }
        });
        jPanel4.add(cmdSpremi);

        cmdZatvori.setMnemonic('X');
        cmdZatvori.setText(resourceMap.getString("cmdZatvori.text")); // NOI18N
        cmdZatvori.setMaximumSize(new java.awt.Dimension(90, 30));
        cmdZatvori.setMinimumSize(new java.awt.Dimension(90, 30));
        cmdZatvori.setName("cmdZatvori"); // NOI18N
        cmdZatvori.setPreferredSize(new java.awt.Dimension(90, 30));
        cmdZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zatvori(evt);
            }
        });
        jPanel4.add(cmdZatvori);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 0, 1));
        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 10, 10));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());

        maticniBroj.setMargin(new java.awt.Insets(2, 2, 2, 2));
        maticniBroj.setName("maticniBroj"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel3.add(maticniBroj, gridBagConstraints);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(125, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(125, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        nazivKorisnika.setMargin(new java.awt.Insets(2, 2, 2, 2));
        nazivKorisnika.setName("nazivKorisnika"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel3.add(nazivKorisnika, gridBagConstraints);

        lokacijaKorisnika.setMargin(new java.awt.Insets(2, 2, 2, 2));
        lokacijaKorisnika.setName("lokacijaKorisnika"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel3.add(lokacijaKorisnika, gridBagConstraints);

        adresaKorisnika.setText(resourceMap.getString("adresaKorisnika.text")); // NOI18N
        adresaKorisnika.setMargin(new java.awt.Insets(2, 2, 2, 2));
        adresaKorisnika.setName("adresaKorisnika"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel3.add(adresaKorisnika, gridBagConstraints);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(125, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        jPanel1.add(jPanel3);

        jPanel6.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 10));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.GridBagLayout());

        emailKorisnika.setText(resourceMap.getString("emailKorisnika.text")); // NOI18N
        emailKorisnika.setMargin(new java.awt.Insets(2, 2, 2, 2));
        emailKorisnika.setName("emailKorisnika"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 265;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel5.add(emailKorisnika, gridBagConstraints);

        telefonKorisnika.setMargin(new java.awt.Insets(2, 2, 2, 2));
        telefonKorisnika.setName("telefonKorisnika"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 265;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel5.add(telefonKorisnika, gridBagConstraints);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(125, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel5.add(jLabel4, gridBagConstraints);

        mobitelKorisnika.setMargin(new java.awt.Insets(2, 2, 2, 2));
        mobitelKorisnika.setName("mobitelKorisnika"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 265;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel5.add(mobitelKorisnika, gridBagConstraints);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(125, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel5.add(jLabel6, gridBagConstraints);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(125, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel5.add(jLabel5, gridBagConstraints);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Zatvori(java.awt.event.ActionEvent evt)                         
    {                             
        try {
            setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(NoviKorisnik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                         

    private void SpremiNovogKorisnika(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SpremiNovogKorisnika
    {//GEN-HEADEREND:event_SpremiNovogKorisnika
        Pro3App app = Pro3App.getApplication();
        app.getContext().getTaskService().execute(new Task(app) 
        {
            @Override
            protected Object doInBackground() throws Exception
            {
                setMessage("Spremam podatke o korisniku");
                Korisnik x = new Korisnik();
                String kljuc = "";

                if(!editMode)
                    kljuc = UUID.randomUUID().toString();
                else
                    kljuc = originalKorisnik.getKljuc();

                x.setKljuc(kljuc);
                x.setNaziv(nazivKorisnika.getText());
                x.setAdresa(adresaKorisnika.getText());
                x.setLokacija(lokacijaKorisnika.getText());
                x.setMaticniBroj(maticniBroj.getText());

                x.setTelefon(telefonKorisnika.getText());
                x.setMobitel(mobitelKorisnika.getText());
                x.setEmail(emailKorisnika.getText());

                EntityTransaction et = proManager.getTransaction();
                et.begin();

                if(!editMode)
                {
                    proManager.persist(x);
                    et.commit();
                    
                    SwingUtilities.invokeLater(new RunNoviKorisnik(NoviKorisnik.this, x, null));
                }
                else
                {
                    proManager.merge(x);
                    et.commit();
                    
                    SwingUtilities.invokeLater(new RunNoviKorisnik(NoviKorisnik.this, x, originalKorisnik));

//                    originalKorisnik.setNaziv(x.getNaziv());
//                    originalKorisnik.setAdresa(x.getAdresa());
//                    originalKorisnik.setLokacija(x.getLokacija());
//                    originalKorisnik.setMaticniBroj(x.getMaticniBroj());
//
//                    originalKorisnik.setMobitel(x.getMobitel());
//                    originalKorisnik.setTelefon(x.getTelefon());
//                    originalKorisnik.setEmail(x.getEmail());

                    //izvorniOkvir.revalidate();
                }

                setMessage("Podaci o korisniku su uspješno spremljeni");
                return null;
            }
        });
        
        
    }//GEN-LAST:event_SpremiNovogKorisnika

    private boolean editMode = false;
    private Korisnik originalKorisnik = null;

    public void IzmjeniKorisnika(JInternalFrame src, Korisnik x)
    {
        editMode = true;
        originalKorisnik = x;

        nazivKorisnika.setText(x.getNaziv());
        adresaKorisnika.setText(x.getAdresa());
        lokacijaKorisnika.setText(x.getLokacija());
        maticniBroj.setText(x.getMaticniBroj());

        telefonKorisnika.setText(x.getTelefon());
        mobitelKorisnika.setText(x.getMobitel());
        emailKorisnika.setText(x.getEmail());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresaKorisnika;
    private javax.swing.JButton cmdSpremi;
    private javax.swing.JButton cmdZatvori;
    private javax.swing.JTextField emailKorisnika;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField lokacijaKorisnika;
    private javax.swing.JTextField maticniBroj;
    private javax.swing.JTextField mobitelKorisnika;
    private javax.swing.JTextField nazivKorisnika;
    private javax.persistence.EntityManager proManager;
    private javax.swing.JTextField telefonKorisnika;
    // End of variables declaration//GEN-END:variables

}
